package com.cong.logiware.constant;

/**
 *
 * @author sunil
 */
public interface QueryConstant {

    //client
    String CLIENT_NAME_SELECT = "CLIENT_NAME_SELECT";
    String CLIENT_NUMBER_SELECT = "CLIENT_NUMBER_SELECT";
    String VENDOR_TP_NAME_SELECT = "VENDOR_TP_NAME_SELECT";
    String VENDOR_TP_NUMBER_SELECT = "VENDOR_TP_NUMBER_SELECT";
    String SSL_CLIENT_NAME_SELECT = "SSL_CLIENT_NAME_SELECT";
    String CARRIER_NAME = "CARRIER_NAME";
    String PORT_ORIGIN = "PORT_ORIGIN";
    String PORT_DESTINATION = "PORT_DESTINATION";
    String TRADE_ROUTE_ID = "TRADE_ROUTE_ID";
    //trucker
    String TRUCKER_SELECT = "TRUCKER_SELECT";
    String LOCATION_SELECT = "LOCATION_SELECT";
    String ACCOUNT_NAME_SELECT = "ACCOUNT_NAME_SELECT";
    //charge
    String CHARGE_CODE_SELECT = "CHARGE_CODE_SELECT";
    String CHARGE_DESC_SELECT = "CHARGE_DESC_SELECT";
    String CHARGE_CODE_DESC_SELECT = "CHARGE_CODE_DESC_SELECT";
    //commodity
    String COMMODITY_CODE_SELECT = "COMMODITY_CODE_SELECT";
    String COMMODITY_DESC_SELECT = "COMMODITY_DESC_SELECT";
    String COMMODITY_TYPE = "COMMODITY_TYPE";
    //type of move
    String TYPE_OF_MOVE_SELECT = "TYPE_OF_MOVE_SELECT";
    String FREQUENCY_OF_SERVICE_SELECT = "FREQUENCY_OF_SERVICE_SELECT";
    String TRANSPORTATION_MODE_SELECT = "TRANSPORTATION_MODE_SELECT";
    String VESSEL_SELECT = "VESSEL_SELECT";
    String BL_FILENUMBER_SELECT = "BL_FILENUMBER_SELECT";
    //unit type
    String UNIT_TYPE_DESC = "UNIT_TYPE_DESC";
    //service
    String SERVICE_DESC = "SERVICE_DESC";
    //port
    String PORTS_SELECT = "PORTS_SELECT";
    String PORT_NAME = "PORT_NAME";
    String SCHED_NUMBER_SELECT = "SCHED_NUMBER_SELECT";
    String PORT_NAME_SELECT = "PORT_NAME_SELECT";
    //airport
    String AIRPORT_SELECT = "AIRPORT_SELECT";
    String AIRPORT_NAME = "AIRPORT_NAME";
    //acount name
    String ACCOUNT_NAME_CONCAT_SELECT = "ACCOUNT_NAME_CONCAT_SELECT";
    //HTS & SCHEDB
    String AES_COMMODITY_CODE = "AES_COMMODITY_CODE";
    String AES_COMMODITY_DESC = "AES_COMMODITY_DESC";
    
}
