package com.cong.logiware.constant;

/**
 *
 * @author BalaMurugan
 */
public interface ReportsConstant {

    String QUOTATION_BUNDLE_PREVIEW = "Quotation Bundle Preview";
    String BOOKING_BUNDLE_PREVIEW = "Booking Bundle Preview";
    String BL_BUNDLE_PREVIEW = "Bl Bundle Preview";
    /*  BL Reports Constants */
    String DEFAULT_CURRENCY = "USD";
    // List reports which have the options of Logo and Rated..

    /*
     * Reports PageInsets LandScape Or A4 Model
     */
    int LAND_SCAPE_WIDTH = 950;
    int LAND_SCAPE_HEIGHT = 850;
    int A4_WIDTH = 900;
    int A4_HEIGHT = 850;
    //REMARKS SEARCH STRINGS
    String BOOKING_CONFIRAMTION_SEARCH_STRING = "BOOKING_CONFIRAMTION";
    String WORK_ORDER_SEARCH_STRING = "WORK_ORDER";
    String REFERENCE_DOCUMENT_SEARCH_STRING = "REFERENCE_DOCUMENT";
    String BL_REMARKS_SEARCH_STRING = "BL";
    String PACKING_LIST_PREDEFINED_REMARKS = "PACKING_LIST_PREDEFF_REMARKS";
    String PACKING_LIST_INS_REMARKS = "PACKING_LIST_INS_REMARKS";
    String COMMERICIAL_INVOICE_INS_REMARKS = "COMMERICIAL_INVOICE_REMARKS";
    String CERTIFICATE_OF_KILN_DRY_REMARKS = "CERTIFICATE_KILN_DRY_REMARKS";
    String DISCLAIMER_DEFAULT_TEXT = "DISCLAIMER_DEFAULT_TEXT";
    String PAYMENT_REMITTANCE_ADDRESS_DEFAULT = "PAYMENT_REMITTANCE_ADDRESS_DEFAULT";
    String ONE_PERCENT_CASH_AGAINST_DOCUMENTS = "ONE_PERCENT_CASH_AGAINST_DOCUMENTS";
    String SALES_TERMS = "SALES_TERMS";
    String PAYMENT_TERMS = "PAYMENT_TERMS";
    String SHIPMENT_ADVICE_REMARKS = "SHIPMENT_ADVICE_REMARKS";
    String BOOKING_BOOKING_INVOICE_1 = "BOOKING_BOOKING_INVOICE_1";
    String BOOKING_BOOKING_INVOICE_2 = "BOOKING_BOOKING_INVOICE_2";
    String BOOKING_BOOKING_CONFIRMATION_2_1 = "BOOKING_BOOKING_CONFIRMATION_2_1";
    String BL_FREIGHT_INVOICE_STANDARD_FORMAT_1 = "BL_FREIGHT_INVOICE_STANDARD_FORMAT_1";
    String BL_FREIGHT_INVOICE_STANDARD_FORMAT_2 = "BL_FREIGHT_INVOICE_STANDARD_FORMAT_2";
    String BL_FREIGHT_INVOICE_STANDARD_FORMAT_IMPORT_1 = "BL_FREIGHT_INVOICE_STANDARD_FORMAT_IMPORT_1";
    String BL_FREIGHT_INVOICE_STANDARD_FORMAT_IMPORT_2 = "BL_FREIGHT_INVOICE_STANDARD_FORMAT_IMPORT_2";
    //LCL - Bill Of Lading
    String BILL_OF_LADING_TERMS = "BILL_OF_LADING_TERMS";
    //REPORT NAME CONSTANTS
    String COMMERICAL_INVOICE_REPORT_NAME = "COMMERCIAL_INVOICE";
    String HOUSE_NON_NEGOTIABLE_RATED_BL_REPORT_NAME = "HOUSE_NON_NEGOTIABLE_RATED_BL";
    String HOUSE_EXPRESS_RELEASE_RATED_BL_REPORT_NAME = "HOUSE_EXPRESS_RELEASE_RATED_BL";
    String HOUSE_ORIGINAL_RATED_BL_REPORT_NAME = "HOUSE_ORIGINAL_RATED_BL";
    String HOUSE_PROOF_RATED_BL_REPORT_NAME = "HOUSE_PROOF_RATED_BL";
    String HOUSE_NON_NEGOTIABLE_RATED_BL_IMPORT_REPORT_NAME = "HOUSE_NON_NEGOTIABLE_RATED_BL_IMPORT";
    String HOUSE_EXPRESS_RELEASE_RATED_BL_IMPORT_REPORT_NAME = "HOUSE_EXPRESS_RELEASE_RATED_BL_IMPORT";
    String HOUSE_ORIGINAL_RATED_BL_IMPORT_REPORT_NAME = "HOUSE_ORIGINAL_RATED_BL_IMPORT";
    String HOUSE_PROOF_RATED_BL_IMPORT_REPORT_NAME = "HOUSE_PROOF_RATED_BL_IMPORT";
    String COST_SHEET_REPORT_NAME = "COST_SHEET";
    String STRAIGHT_BL_DESC1 = "STRAIGHT_BL_DESC1";
    String STRAIGHT_BL_DESC2 = "STRAIGHT_BL_DESC2";
    String STRAIGHT_BL_DESC3 = "STRAIGHT_BL_DESC3";
    String STRAIGHT_BL_DESC4 = "STRAIGHT_BL_DESC4";
    String STRAIGHT_BL_DESC5 = "STRAIGHT_BL_DESC5";
    String STRAIGHT_BL_DESC6 = "STRAIGHT_BL_DESC6";
    String STRAIGHT_BL_DESC7 = "STRAIGHT_BL_DESC7";
    String INTENT_FOR_VEHICLE_EXPORTS = "INTENT_FOR_VEHICLE_EXPORTS";
    String SAILING_CONFIRMATION1 = "SAILING_CONFIRMATION1";
    String SAILING_CONF_FOOTER = "SAILING_CONF_FOOTER";
    String ARRIVAL_BOTTOM_REMARKS = "ARRIVAL_BOTTOM_REMARKS";
    String PRE_ARRIVAL_NOTICE = "Pre Arrival Notice";
    //CERTIFICATE OF ORIGIN CONSTANTS
    String SIGNATURE_OF_OWNER_OR_AGENT = "Signature of Owner or Agent";
    String SIGNATURE_OF_NOTARY_PUBLIC = "Notary Public";
    String SIGNATURE_OF_SECRETARY = "Secretary";
    String PRODUCT_OF_COUNTRY_DEFAULT = "UNITED STATES OF AMERICA";
    String AFFIDAVIT_OF_ORIGIN_DEFAULT_REMARKS = "AFFIDAVIT_OF_ORIGIN_REMARKS";
    String NOTARY_PUBLIC_DEFAULT_REMARKS = "SWORN TO BEFORE ME ON";
    String CERTIFICATE_NOTARY_DEFAULT_REMARKS1 = "fcl_report_co_notary_field1";
    String CERTIFICATE_NOTARY_DEFAULT_REMARKS2 = "fcl_report_co_notary_field2";
    String CERTIFICATE_NOTARY_DEFAULT_REMARKS3 = "fcl_report_co_notary_field3";
    String CERTIFICATE_NOTARY_DEFAULT_REMARKS4 = "fcl_report_co_notary_field4";
    String CERTIFICATE_ISSUED_BY = "fcl_report_co_issued_by";
    String CHAMBER_OF_COMMERCE_DEFAULT_REMARKS = "CHAMBER_OF_COMMERCE_REMARKS";
    String COMPANY_NAME = "company_name";
    String COMPANY_NUMBER = "company_number";
    //BANK DRAFT
    String OTHER_INSTRUCTIONS = "OTHER INSTRUCTIONS";
    String SIGNATURE = "SIGNATURE";
    //DEACLARATION OF NON WOOD PACKING LIST
    String NON_WOOD_PACKING_REMARKS = "NON_WOOD_PACKING_REMARKS";
    // BENEFICIARY CERTIFICATE CONSTANTS
    String BENEFICIARY_CERTIFICATE_REMARKS = "Beneficiary Certificate";
    //CERTIFICATE OF QUALITY 1
    String CERTIFICATE_OF_QUALITY_V1_REMARKS = "CERTIFICATE_OF_QUALITY_V1_REMARKS";
    //CERTIFICATE OF QUALITY 2
    String CERTIFICATE_OF_QUALITY_V2_REMARKS = "CERTIFICATE_OF_QUALITY_V2_REMARKS";
    String QUALITY_CERTIFICATE_PERU_COMPANY_NAME = "QUALITY_CERTIFICATE_PERU_COMPANY_NAME";
    String QUALITY_CERTIFICATE_PERU_PORT = "QUALITY_CERTIFICATE_PERU_PORT";
    String QUALITY_CERTIFICATE_FOR_PERU_CLAUSE = "QUALITY_CERTIFICATE_FOR_PERU_CLAUSE";
    String QUALITY_CERTIFICATE_FOR_PERU_CLAUSE_2 = "QUALITY_CERTIFICATE_FOR_PERU_CLAUSE_2";
    String QUALITY_CERTIFICATE_PERU_LICENSE = "QUALITY_CERTIFICATE_PERU_LICENSE";
    //SALES ORDER REPORTS PAN
    String SO_PO_COMPANY_NUMBER = "SO_COMPANY_NUMBER";
    String SO_PO_COMPANY_NAME = "SO_COMPANY_NAME";
    String SO_PO_EST_TITLE = "SO_EST_TITLE";
    String SO_PO_EST_PAYMENT_INFO = "SO_EST_PAYMENT_INFO";
    String SO_PO_EST_PRICE_GAURANTEE = "SO_EST_PRICE_GAURANTEE";
    String SO_PO_EST_CLAUSES = "SO_EST_CLAUSES";
    String SO_PO_EST_NOTES = "SO_EST_NOTES";
    String SO_PO_TANDC_PAYMENT_INFO = "SO_PO_TANDC_PAYMENT_INFO";
    /*
     * Print Configuration
     */
    String P_TRADING_PARTNER = "TP";
    String P_DOCUMENT = "DOCUMENT";
    String P_USER = "USER";
    String S_ORIGIN = "ORIGIN";
    String S_NOTARY = "NOTARY";
    String S_CHAMBER = "CHAMBER";
    String S_KILN_DRY = "KILN_DRY";
    String S_CO_SAVANNAH = "CO_SAVANNAH";
    String S_CO_SAVANNAH_STAMP = "CO_SAVANNAH_STAMP";
    String S_WOOD_PACK = "WOOD_PACK";
    String S_BILL_OF_EXCHANGE = "BILL_OF_EXCHANGE";
    String S_LETTER_OF_TRANSMITTAL = "LETTER_OF_TRANSMITTAL";
    String S_BANK_DRAFT = "BANK_DRAFT";
    String S_BENEFICIARY = "BENEFICIARY";
    String S_PACKING_LIST = "PACKING";
    String S_COQ_VERSION_1 = "COQ_VERSION_1";
    String S_COQ_VERSION_2_A = "COQ_VERSION_2_A";
    String S_COQ_VERSION_2_B = "COQ_VERSION_2_B";
    String COMMERCIAL_INVOICE_REMARK = "COMMERCIAL_INVOICE_REMARK";
    String COMMERCIAL_INVOICE_FORMAT_3_REMARK = "COMMERCIAL_INVOICE_FORMAT_3_REMARK";
    String COMMERCIAL_INVOICE_FORMAT_3_SAMPLE = "COMMERCIAL_INVOICE_FORMAT_3_SAMPLE";

//    Air
    String TSA_APPROVED_PROGARM = "TSA_APPROVED_PROGRAM";
    String SHIPPER_DECLARATION_FOR_DANGEROUS_GOODS = "SHIPPER_DECLARATION_FOR_DANGEROUS_GOODS";

    String IMO_DANGEROUS_GOODS_DECLARATION = "IMO_DANGEROUS_GOODS_DECLARATION";
    String IMPORT_NOTE = "IMPORT_NOTE";
    String DELIVERY_PICKUP_ORDER = "DELIVERY_PICKUP_ORDER";
    String ARRIVAL_NOTICE_2 = "ARRIVAL_NOTICE_2";
    String LCL_IMP_BK_AN = "LCL_IMP_BK_AN";
    String ISRAEL_CERTIFICATE_NOTE_1 = "ISRAEL_CERTIFICATE_NOTE_1";
    String ISRAEL_CERTIFICATE_NOTE_2 = "ISRAEL_CERTIFICATE_NOTE_2";
    String ISRAEL_CERTIFICATE_NOTE_3 = "ISRAEL_CERTIFICATE_NOTE_3";
    String ISRAEL_CERTIFICATE_NOTE_4 = "ISRAEL_CERTIFICATE_NOTE_4";
    String ISRAEL_CERTIFICATE_NOTE_5 = "ISRAEL_CERTIFICATE_NOTE_5";
}
